spring:
  application:
    name: hello-boot
  jmx:
    enabled: true
    defaultDomain: hello-boot
endpoints:
  jmx:
    domain: hello-boot

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/