spring:
  application:
    name: hello-spring
  jmx:
    enabled: true
    defaultDomain: hello-spring
endpoints:
  jmx:
    domain: hello-spring
server:
  port: 8081


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9999/eureka/